"""add user sources column to queries

Revision ID: 5bf146fc3d97
Revises: 8e9af4c44607
Create Date: 2026-04-16 17:14:39.985846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5bf146fc3d97'
down_revision: Union[str, None] = '8e9af4c44607'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('queries', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'queries', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'queries', type_='foreignkey')
    op.drop_column('queries', 'user_id')
    # ### end Alembic commands ###
